{
 "title": "Weathercloud",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "11m",
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Temperature\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp)\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Temerature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Temperature\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp)\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Humidty\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp)\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Humidty\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp)\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Bar\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp)\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Bar\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp)\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Rain\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp)\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Windspeed\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp)\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Rain Distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Rain\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp)\nORDER BY Timestamp"
    }
   ]
  }
 ]
}